### ISSUE TITLE
could upload the requirement.txt of each package of pip ?

### ISSUE THREAD

**Issue by Rockyzsu** [ai2010/machine_learning_for_the_web#3]
on chapter 6 i running django with 1.7,1.8,1.9, or 2.0 but none of them can run the code properply.
Looks like diff version of restframework or django version issue.

    from django.shortcuts import render_to_response, RequestContext
ImportError: cannot import name RequestContext

or     from django.urls import (  # noqa
ImportError: No module named urls

**Comment by ai2010** [comment]
Hi,

I just addedd the requirement.txt and updated the files accordingly. All the examples (chapters 6,7 and 8) are working using Django 1.10. Let me know if you face any problem.

**Comment by Rockyzsu** [comment]
Thanks. Closed
